sentry:
  #debug: true # 디버그 모드
  enable-tracing: true
  send-default-pii: true # 사용자 정보 기록
  environment: development # 개발환경 / environment=production
  logging: # 범위
    minimum-event-level: "WARN"
    minimum-breadcrumb-level: "INFO"
  dsn: https://56ab2b3b2d344c9cac66ca3d3fa4efe1@o4504986976124928.ingest.sentry.io/4504986986217472
  sample-rate: 0.5 # 샘플링 비율 1=100% 다 보냄
  #traces-sample-rate # 트랜잭션 비율 설정


cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: villages-3
    credentials:
      access-key: AKIAQQ5QPUSNTPXXS7BC
      secret-key: 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
    stack:
      auto: false

#meta:
#  bucket: ${bucket}
#  access-key: ${access-key}
#  secret-key: ${secret-key}
#  staticval: ${static}

server:
  # port: 8080
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 3600

spring:
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

logging:
  level:
    # 로그레벨 설정 DEBUG로 개발하고 INFO로 배포한다.
    '[shop.mtcoding.securityapp]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기
# mybatis:
#   mapper-locations:
#   - classpath:mapper/**.xml
#   configuration:
#     map-underscore-to-camel-case: true
